version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: helios_backend
    ports:
      - "8001:8000" # Host 8001 -> Container 8000 (Matches frontend API calls)
    volumes:
      - ./models:/app/models
      - ./dataset:/app/dataset
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: helios_frontend
    ports:
      - "3000:80" # Host 3000 -> Container 80
    depends_on:
      - backend
    restart: always
